version: '3.9'
services:
  database:
    image: postgres:15 # Sử dụng image PostgreSQL chính thức
    container_name: database
    environment:
      POSTGRES_USER: taikhau
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nhom1-database
    ports:
      - "5432:5432" # Ánh xạ cổng 5432 của container sang cổng 5432 của host
    volumes:
      - db_data:/var/lib/postgresql/data # Lưu trữ dữ liệu bên ngoài container để đảm bảo dữ liệu không mất đi khi container bị xóa

  backend:
    image: qu1et/nhom1-backend:latest
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/nhom1-database
      SPRING_DATASOURCE_USERNAME: taikhau
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - database
    ports:
      - "8080:8080"

  frontend:
    image: qu1et/nhom1-frontend:latest
    container_name: frontend
    ports:
      - "10000:9090"

volumes:
  db_data:
