name: Build, Test, and Analyze Backend with SonarQube

on:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: [self-hosted, backend-runner]

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      # Kiểm tra kết nối đến PostgreSQL đang chạy sẵn
      - name: Wait for Existing Database
        run: |
          until pg_isready -h localhost -p 5432 -U taikhau -d nhom1-database; do
            echo "Waiting for existing database to be ready..."
            sleep 5
          done
       
      # Backend Build and Analysis
      - name: Set executable permission for gradlew
        run: chmod +x backend/gradlew

      # Build backend
      - name: Build Backend
        run: |
          cd backend
          ./gradlew build
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nhom1-database
          SPRING_DATASOURCE_USERNAME: taikhau
          SPRING_DATASOURCE_PASSWORD: 123

      # Run tests for backend
      - name: Run Backend Tests
        run: |
          cd backend
          ./gradlew test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nhom1-database
          SPRING_DATASOURCE_USERNAME: taikhau
          SPRING_DATASOURCE_PASSWORD: 123

      # Run SonarQube analysis
      - name: SonarQube Analysis
        run: |
          cd backend
          ./gradlew sonar --info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/nhom1-database
          SPRING_DATASOURCE_USERNAME: taikhau
          SPRING_DATASOURCE_PASSWORD: 123

          # Build and push backend image
      - name: Build and Push Backend Image
        run: |
          docker build -t nhom1-backend ./backend
          docker tag nhom1-backend qu1et/nhom1-backend:latest
          docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
          docker push qu1et/nhom1-backend:latest
  deploy:
    name: Deploy Application
    needs: build
    runs-on: [self-hosted, backend-runner]
    steps:
      # Xóa các container/dịch vụ hiện có
      - name: Remove Existing Containers
        run: docker-compose down

      # Pull Docker images
      - name: Pull Docker Images
        run: |
          docker pull qu1et/nhom1-backend:latest
      - name: Image scan
        run: |
          trivy image qu1et/nhom1-backend:latest > trivyimagedeploybackend.txt
      - name: Deploy with Docker Compose
        run: docker-compose up -d database backend